//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace dnSpy.Contracts.Logic.Properties {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o recompile su proyecto de VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class dnSpy_Contracts_Logic_Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal dnSpy_Contracts_Logic_Resources() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("dnSpy.Contracts.Logic.Properties.dnSpy.Contracts.Logic.Resources", typeof(dnSpy_Contracts_Logic_Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Value must be a boolean value (True or False).
        /// </summary>
        internal static string InvalidBoolean {
            get {
                return ResourceManager.GetString("InvalidBoolean", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a A character must be enclosed in single quotes (&apos;).
        /// </summary>
        internal static string InvalidChar {
            get {
                return ResourceManager.GetString("InvalidChar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Value must be a DateTime.
        /// </summary>
        internal static string InvalidDateTime {
            get {
                return ResourceManager.GetString("InvalidDateTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Value must be a Decimal.
        /// </summary>
        internal static string InvalidDecimal {
            get {
                return ResourceManager.GetString("InvalidDecimal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Value must be a 64-bit floating point number.
        /// </summary>
        internal static string InvalidDouble {
            get {
                return ResourceManager.GetString("InvalidDouble", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Unknown character escape sequence: \{0}.
        /// </summary>
        internal static string InvalidEscapeSequence {
            get {
                return ResourceManager.GetString("InvalidEscapeSequence", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Unknown string escape sequence: \{0}.
        /// </summary>
        internal static string InvalidEscapeSequence2 {
            get {
                return ResourceManager.GetString("InvalidEscapeSequence2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a A hex string must contain only hex digits: 0-9 and A-F.
        /// </summary>
        internal static string InvalidHexCharacter {
            get {
                return ResourceManager.GetString("InvalidHexCharacter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a A hex string must contain an even number of hex digits.
        /// </summary>
        internal static string InvalidHexStringSize {
            get {
                return ResourceManager.GetString("InvalidHexStringSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a The value is not a hexadecimal or decimal integer.
        /// </summary>
        internal static string InvalidInteger1 {
            get {
                return ResourceManager.GetString("InvalidInteger1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a The value is too small.
        /// </summary>
        internal static string InvalidInteger2 {
            get {
                return ResourceManager.GetString("InvalidInteger2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a The value is too big.
        /// </summary>
        internal static string InvalidInteger3 {
            get {
                return ResourceManager.GetString("InvalidInteger3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Value must be between {0} and {1} (0x{1:X}) inclusive.
        /// </summary>
        internal static string InvalidInteger4 {
            get {
                return ResourceManager.GetString("InvalidInteger4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Value must be between {0} ({2}0x{0:X}) and {1} (0x{1:X}) inclusive.
        /// </summary>
        internal static string InvalidInteger5 {
            get {
                return ResourceManager.GetString("InvalidInteger5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Value in list can&apos;t be empty.
        /// </summary>
        internal static string InvalidListValue {
            get {
                return ResourceManager.GetString("InvalidListValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a List elements must be separated with commas.
        /// </summary>
        internal static string InvalidListValue2 {
            get {
                return ResourceManager.GetString("InvalidListValue2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Value must be a 32-bit floating point number.
        /// </summary>
        internal static string InvalidSingle {
            get {
                return ResourceManager.GetString("InvalidSingle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a A string must contain the value &apos;null&apos; or must be enclosed in double quotes (&quot;).
        /// </summary>
        internal static string InvalidString1 {
            get {
                return ResourceManager.GetString("InvalidString1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a A string must be enclosed in double quotes (&quot;).
        /// </summary>
        internal static string InvalidString2 {
            get {
                return ResourceManager.GetString("InvalidString2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Value must be a TimeSpan.
        /// </summary>
        internal static string InvalidTimeSpan {
            get {
                return ResourceManager.GetString("InvalidTimeSpan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Only non-negative integers are allowed.
        /// </summary>
        internal static string InvalidUnsignedInteger1 {
            get {
                return ResourceManager.GetString("InvalidUnsignedInteger1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a The value is not an unsigned hexadecimal or decimal integer.
        /// </summary>
        internal static string InvalidUnsignedInteger2 {
            get {
                return ResourceManager.GetString("InvalidUnsignedInteger2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Value must be between {0} and {1} (0x{1:X}) inclusive.
        /// </summary>
        internal static string InvalidUnsignedInteger3 {
            get {
                return ResourceManager.GetString("InvalidUnsignedInteger3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Value must be between {0} (0x{0:X}) and {1} (0x{1:X}) inclusive.
        /// </summary>
        internal static string InvalidUnsignedInteger4 {
            get {
                return ResourceManager.GetString("InvalidUnsignedInteger4", resourceCulture);
            }
        }
    }
}
