//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace dnSpy.Contracts.DnSpy.Properties {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o recompile su proyecto de VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class dnSpy_Contracts_DnSpy_Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal dnSpy_Contracts_DnSpy_Resources() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("dnSpy.Contracts.DnSpy.Properties.dnSpy.Contracts.DnSpy.Resources", typeof(dnSpy_Contracts_DnSpy_Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a All Files.
        /// </summary>
        public static string AllFiles {
            get {
                return ResourceManager.GetString("AllFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a An error occurred:
        ///
        ///{0}.
        /// </summary>
        public static string AnErrorOccurred {
            get {
                return ResourceManager.GetString("AnErrorOccurred", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a _Cancel.
        /// </summary>
        public static string Button_Cancel {
            get {
                return ResourceManager.GetString("Button_Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Could not convert &apos;{0}&apos;.
        /// </summary>
        public static string CouldNotConvert {
            get {
                return ResourceManager.GetString("CouldNotConvert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Could not convert it from a string: {0}.
        /// </summary>
        public static string CouldNotConvertFromString {
            get {
                return ResourceManager.GetString("CouldNotConvertFromString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Could not deserialize data: {0}.
        /// </summary>
        public static string CouldNotDeserializeData {
            get {
                return ResourceManager.GetString("CouldNotDeserializeData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a .NET Executables.
        /// </summary>
        public static string Files_DotNetExecutables {
            get {
                return ResourceManager.GetString("Files_DotNetExecutables", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a .NET NetModules.
        /// </summary>
        public static string Files_DotNetNetModules {
            get {
                return ResourceManager.GetString("Files_DotNetNetModules", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Executables.
        /// </summary>
        public static string Files_Executables {
            get {
                return ResourceManager.GetString("Files_Executables", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Images.
        /// </summary>
        public static string Files_Images {
            get {
                return ResourceManager.GetString("Files_Images", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Strong Name Key Files.
        /// </summary>
        public static string Files_StrongNameKeyFiles {
            get {
                return ResourceManager.GetString("Files_StrongNameKeyFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a XML Files.
        /// </summary>
        public static string Files_XmlFiles {
            get {
                return ResourceManager.GetString("Files_XmlFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Invalid GUID.
        /// </summary>
        public static string InvalidGuid {
            get {
                return ResourceManager.GetString("InvalidGuid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a The new data is not an image list..
        /// </summary>
        public static string NewDataNotImageList {
            get {
                return ResourceManager.GetString("NewDataNotImageList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a {0} does not have a TypeConverter and can&apos;t be converted from a string..
        /// </summary>
        public static string NoTypeConverter {
            get {
                return ResourceManager.GetString("NoTypeConverter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a {0} bytes.
        /// </summary>
        public static string NumberOfBytes {
            get {
                return ResourceManager.GetString("NumberOfBytes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a {0} bytes, Type = {1}.
        /// </summary>
        public static string NumberOfBytesAndType {
            get {
                return ResourceManager.GetString("NumberOfBytesAndType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Resource type can&apos;t be changed.
        /// </summary>
        public static string ResourceTypeCantBeChanged {
            get {
                return ResourceManager.GetString("ResourceTypeCantBeChanged", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Save Resource.
        /// </summary>
        public static string SaveResource {
            get {
                return ResourceManager.GetString("SaveResource", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Save Resources.
        /// </summary>
        public static string SaveResources {
            get {
                return ResourceManager.GetString("SaveResources", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Search column: {0}.
        /// </summary>
        public static string Search_SearchColumnHelpText {
            get {
                return ResourceManager.GetString("Search_SearchColumnHelpText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Use &apos;{0}&apos; to invert the match, eg. {1}.
        /// </summary>
        public static string Search_SearchColumnInvertMatchHelpText {
            get {
                return ResourceManager.GetString("Search_SearchColumnInvertMatchHelpText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Value must be type {0}.
        ///Error: {1}.
        /// </summary>
        public static string ValueMustBeType {
            get {
                return ResourceManager.GetString("ValueMustBeType", resourceCulture);
            }
        }
    }
}
