//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace dnSpy.BamlDecompiler.Properties {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o recompile su proyecto de VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class dnSpy_BamlDecompiler_Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal dnSpy_BamlDecompiler_Resources() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("dnSpy.BamlDecompiler.Properties.dnSpy.BamlDecompiler.Resources", typeof(dnSpy_BamlDecompiler_Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a All Files.
        /// </summary>
        public static string AllFiles {
            get {
                return ResourceManager.GetString("AllFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a BAML File.
        /// </summary>
        public static string BAMLFile {
            get {
                return ResourceManager.GetString("BAMLFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a BAML Decompiler.
        /// </summary>
        public static string BamlOptionDlgTab {
            get {
                return ResourceManager.GetString("BamlOptionDlgTab", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Disassemble BAML.
        /// </summary>
        public static string BamlSettings_DisassembleBAML {
            get {
                return ResourceManager.GetString("BamlSettings_DisassembleBAML", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a One attribute per line.
        /// </summary>
        public static string BamlSettings_NewLineOnAttributes {
            get {
                return ResourceManager.GetString("BamlSettings_NewLineOnAttributes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Use tabs.
        /// </summary>
        public static string BamlSettings_UseTabs {
            get {
                return ResourceManager.GetString("BamlSettings_UseTabs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Disassemble BAML.
        /// </summary>
        public static string DisassembleBAMLCommand {
            get {
                return ResourceManager.GetString("DisassembleBAMLCommand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Attached event &apos;{0}&apos;..
        /// </summary>
        public static string Error_AttachedEvent {
            get {
                return ResourceManager.GetString("Error_AttachedEvent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Class &apos;{0}&apos; has IComponentConnector.Connect method, but cannot be parsed..
        /// </summary>
        public static string Error_IComponentConnectorConnectCannotBeParsed {
            get {
                return ResourceManager.GetString("Error_IComponentConnectorConnectCannotBeParsed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Class &apos;{0}&apos; has IStyleConnector.Connect method, but cannot be parsed..
        /// </summary>
        public static string Error_IStyleConnectorConnectCannotBeParsed {
            get {
                return ResourceManager.GetString("Error_IStyleConnectorConnectCannotBeParsed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Unknown connection ID: {0}.
        /// </summary>
        public static string Error_UnknownConnectionId {
            get {
                return ResourceManager.GetString("Error_UnknownConnectionId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a &apos;{0}&apos; is prefix for the global namespace..
        /// </summary>
        public static string Msg_GlobalNamespace {
            get {
                return ResourceManager.GetString("Msg_GlobalNamespace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a BAML decompiler.
        /// </summary>
        public static string Plugin_ShortDescription {
            get {
                return ResourceManager.GetString("Plugin_ShortDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a _Save BAML....
        /// </summary>
        public static string SaveBAML {
            get {
                return ResourceManager.GetString("SaveBAML", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a _Save XAML....
        /// </summary>
        public static string SaveXAML {
            get {
                return ResourceManager.GetString("SaveXAML", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Saving....
        /// </summary>
        public static string Saving {
            get {
                return ResourceManager.GetString("Saving", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a XAML File.
        /// </summary>
        public static string XAMLFile {
            get {
                return ResourceManager.GetString("XAMLFile", resourceCulture);
            }
        }
    }
}
