//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace dnSpy.Analyzer.Properties {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o recompile su proyecto de VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class dnSpy_Analyzer_Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal dnSpy_Analyzer_Resources() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("dnSpy.Analyzer.Properties.dnSpy.Analyzer.Resources", typeof(dnSpy_Analyzer_Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Analy_ze.
        /// </summary>
        public static string AnalyzeCommand {
            get {
                return ResourceManager.GetString("AnalyzeCommand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Analyzer.
        /// </summary>
        public static string AnalyzerWindowTitle {
            get {
                return ResourceManager.GetString("AnalyzerWindowTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Applied To.
        /// </summary>
        public static string AppliedToTreeNode {
            get {
                return ResourceManager.GetString("AppliedToTreeNode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Assigned By.
        /// </summary>
        public static string AssignedByTreeNode {
            get {
                return ResourceManager.GetString("AssignedByTreeNode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Cop_y.
        /// </summary>
        public static string CopyCommand {
            get {
                return ResourceManager.GetString("CopyCommand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Dbl Click.
        /// </summary>
        public static string DoubleClick {
            get {
                return ResourceManager.GetString("DoubleClick", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Exposed By.
        /// </summary>
        public static string ExposedByTreeNode {
            get {
                return ResourceManager.GetString("ExposedByTreeNode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Extension Methods.
        /// </summary>
        public static string ExtensionMethodsTreeNode {
            get {
                return ResourceManager.GetString("ExtensionMethodsTreeNode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Go to Reference.
        /// </summary>
        public static string GoToReferenceCommand {
            get {
                return ResourceManager.GetString("GoToReferenceCommand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Show Reference in Method.
        /// </summary>
        public static string GoToReferenceInCodeCommand {
            get {
                return ResourceManager.GetString("GoToReferenceInCodeCommand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Show Reference in Method (New _Tab).
        /// </summary>
        public static string GoToReferenceInCodeNewTabCommand {
            get {
                return ResourceManager.GetString("GoToReferenceInCodeNewTabCommand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Go to Reference (New Ta_b).
        /// </summary>
        public static string GoToReferenceNewTabCommand {
            get {
                return ResourceManager.GetString("GoToReferenceNewTabCommand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a hides.
        /// </summary>
        public static string HidesParent {
            get {
                return ResourceManager.GetString("HidesParent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Implemented By.
        /// </summary>
        public static string ImplementedByTreeNode {
            get {
                return ResourceManager.GetString("ImplementedByTreeNode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Instantiated By.
        /// </summary>
        public static string InstantiatedByTreeNode {
            get {
                return ResourceManager.GetString("InstantiatedByTreeNode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Overridden By.
        /// </summary>
        public static string OverriddenByTreeNode {
            get {
                return ResourceManager.GetString("OverriddenByTreeNode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Overrides.
        /// </summary>
        public static string OverridesTreeNode {
            get {
                return ResourceManager.GetString("OverridesTreeNode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Analyzes assemblies.
        /// </summary>
        public static string Plugin_ShortDescription {
            get {
                return ResourceManager.GetString("Plugin_ShortDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Raised By.
        /// </summary>
        public static string RaisedByTreeNode {
            get {
                return ResourceManager.GetString("RaisedByTreeNode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Read By.
        /// </summary>
        public static string ReadByTreeNode {
            get {
                return ResourceManager.GetString("ReadByTreeNode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a _Remove.
        /// </summary>
        public static string RemoveCommand {
            get {
                return ResourceManager.GetString("RemoveCommand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Searching....
        /// </summary>
        public static string Searching {
            get {
                return ResourceManager.GetString("Searching", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Shift+Dbl Click.
        /// </summary>
        public static string ShiftDoubleClick {
            get {
                return ResourceManager.GetString("ShiftDoubleClick", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ctrl+C.
        /// </summary>
        public static string ShortCutKeyCtrlC {
            get {
                return ResourceManager.GetString("ShortCutKeyCtrlC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ctrl+Shift+R.
        /// </summary>
        public static string ShortCutKeyCtrlShiftR {
            get {
                return ResourceManager.GetString("ShortCutKeyCtrlShiftR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Del.
        /// </summary>
        public static string ShortCutKeyDelete {
            get {
                return ResourceManager.GetString("ShortCutKeyDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Show Tokens.
        /// </summary>
        public static string ShowMetadataTokensCommand {
            get {
                return ResourceManager.GetString("ShowMetadataTokensCommand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Single-click expands nodes.
        /// </summary>
        public static string SingleClickExpandNodes {
            get {
                return ResourceManager.GetString("SingleClickExpandNodes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Syntax Highlight.
        /// </summary>
        public static string SyntaxHighlightCommand {
            get {
                return ResourceManager.GetString("SyntaxHighlightCommand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Used By.
        /// </summary>
        public static string UsedByTreeNode {
            get {
                return ResourceManager.GetString("UsedByTreeNode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Uses.
        /// </summary>
        public static string UsesTreeNode {
            get {
                return ResourceManager.GetString("UsesTreeNode", resourceCulture);
            }
        }
    }
}
