//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace dnSpy.Scripting.Roslyn.Properties {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o recompile su proyecto de VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class dnSpy_Scripting_Roslyn_Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal dnSpy_Scripting_Roslyn_Resources() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("dnSpy.Scripting.Roslyn.Properties.dnSpy.Scripting.Roslyn.Resources", typeof(dnSpy_Scripting_Roslyn_Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a All Files.
        /// </summary>
        public static string AllFiles {
            get {
                return ResourceManager.GetString("AllFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Clear Screen.
        /// </summary>
        public static string ClearScreenCommand {
            get {
                return ResourceManager.GetString("ClearScreenCommand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a + additional {0} error.
        /// </summary>
        public static string CompilationAdditionalError {
            get {
                return ResourceManager.GetString("CompilationAdditionalError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a + additional {0} errors.
        /// </summary>
        public static string CompilationAdditionalErrors {
            get {
                return ResourceManager.GetString("CompilationAdditionalErrors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Copy Code.
        /// </summary>
        public static string CopyCodeCommand {
            get {
                return ResourceManager.GetString("CopyCodeCommand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Cop_y.
        /// </summary>
        public static string CopyCommand {
            get {
                return ResourceManager.GetString("CopyCommand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a C# Script Files.
        /// </summary>
        public static string CSharpScriptFiles {
            get {
                return ResourceManager.GetString("CSharpScriptFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Cu_t.
        /// </summary>
        public static string CutCommand {
            get {
                return ResourceManager.GetString("CutCommand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Show next command.
        /// </summary>
        public static string HelpAltDown {
            get {
                return ResourceManager.GetString("HelpAltDown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Show previous command.
        /// </summary>
        public static string HelpAltUp {
            get {
                return ResourceManager.GetString("HelpAltUp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Clear the script editor.
        /// </summary>
        public static string HelpClearDescription {
            get {
                return ResourceManager.GetString("HelpClearDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Select input text. Press again to select all text.
        /// </summary>
        public static string HelpCtrlA {
            get {
                return ResourceManager.GetString("HelpCtrlA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Show next command matching the current input text.
        /// </summary>
        public static string HelpCtrlAltDown {
            get {
                return ResourceManager.GetString("HelpCtrlAltDown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Show previous command matching the current input text.
        /// </summary>
        public static string HelpCtrlAltUp {
            get {
                return ResourceManager.GetString("HelpCtrlAltUp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Execute the command.
        /// </summary>
        public static string HelpCtrlEnter {
            get {
                return ResourceManager.GetString("HelpCtrlEnter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Execute the command.
        /// </summary>
        public static string HelpEnter {
            get {
                return ResourceManager.GetString("HelpEnter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Clear current input.
        /// </summary>
        public static string HelpEscape {
            get {
                return ResourceManager.GetString("HelpEscape", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Display the help.
        /// </summary>
        public static string HelpHelpDescription {
            get {
                return ResourceManager.GetString("HelpHelpDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Keyboard shortcuts:.
        /// </summary>
        public static string HelpKeyboardShortcuts {
            get {
                return ResourceManager.GetString("HelpKeyboardShortcuts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a REPL commands:.
        /// </summary>
        public static string HelpReplCommands {
            get {
                return ResourceManager.GetString("HelpReplCommands", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Reset the execution environment.
        /// </summary>
        public static string HelpResetDescription {
            get {
                return ResourceManager.GetString("HelpResetDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Load and execute a script, #load &quot;myscript.csx&quot;.
        /// </summary>
        public static string HelpScriptDirective_load {
            get {
                return ResourceManager.GetString("HelpScriptDirective_load", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Add a reference, either an assembly or a path to a file on disk or a path relative to the dnSpy or user directory, #r &quot;myfile.dll&quot;.
        /// </summary>
        public static string HelpScriptDirective_r {
            get {
                return ResourceManager.GetString("HelpScriptDirective_r", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Script directives:.
        /// </summary>
        public static string HelpScriptDirectives {
            get {
                return ResourceManager.GetString("HelpScriptDirectives", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Insert a new line.
        /// </summary>
        public static string HelpShiftEnter {
            get {
                return ResourceManager.GetString("HelpShiftEnter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Type &quot;#help&quot; for more information..
        /// </summary>
        public static string HelpString {
            get {
                return ResourceManager.GetString("HelpString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Loading context from &apos;{0}&apos;..
        /// </summary>
        public static string LoadingContextFromFile {
            get {
                return ResourceManager.GetString("LoadingContextFromFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a _Paste.
        /// </summary>
        public static string PasteCommand {
            get {
                return ResourceManager.GetString("PasteCommand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Scripting.
        /// </summary>
        public static string Plugin_ShortDescription {
            get {
                return ResourceManager.GetString("Plugin_ShortDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Save.
        /// </summary>
        public static string Repl_Save_ToolTip {
            get {
                return ResourceManager.GetString("Repl_Save_ToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Toggle Word Wrap.
        /// </summary>
        public static string Repl_WordWrap_ToolTip {
            get {
                return ResourceManager.GetString("Repl_WordWrap_ToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Resetting execution engine..
        /// </summary>
        public static string ResettingExecutionEngine {
            get {
                return ResourceManager.GetString("ResettingExecutionEngine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Save Code....
        /// </summary>
        public static string SaveCodeCommand {
            get {
                return ResourceManager.GetString("SaveCodeCommand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Save....
        /// </summary>
        public static string SaveCommand {
            get {
                return ResourceManager.GetString("SaveCommand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Clear Screen.
        /// </summary>
        public static string Script_ToolTip_ClearScreen {
            get {
                return ResourceManager.GetString("Script_ToolTip_ClearScreen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a History Next.
        /// </summary>
        public static string Script_ToolTip_HistoryNext {
            get {
                return ResourceManager.GetString("Script_ToolTip_HistoryNext", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a History Previous.
        /// </summary>
        public static string Script_ToolTip_HistoryPrevious {
            get {
                return ResourceManager.GetString("Script_ToolTip_HistoryPrevious", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Reset.
        /// </summary>
        public static string Script_ToolTip_Reset {
            get {
                return ResourceManager.GetString("Script_ToolTip_Reset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Alt+Down Arrow.
        /// </summary>
        public static string ShortCutKeyAltDown {
            get {
                return ResourceManager.GetString("ShortCutKeyAltDown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Alt+Up Arrow.
        /// </summary>
        public static string ShortCutKeyAltUp {
            get {
                return ResourceManager.GetString("ShortCutKeyAltUp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ctrl+A.
        /// </summary>
        public static string ShortCutKeyCtrlA {
            get {
                return ResourceManager.GetString("ShortCutKeyCtrlA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ctrl+Alt+Down Arrow.
        /// </summary>
        public static string ShortCutKeyCtrlAltDown {
            get {
                return ResourceManager.GetString("ShortCutKeyCtrlAltDown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ctrl+Alt+I.
        /// </summary>
        public static string ShortCutKeyCtrlAltI {
            get {
                return ResourceManager.GetString("ShortCutKeyCtrlAltI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ctrl+Alt+N.
        /// </summary>
        public static string ShortCutKeyCtrlAltN {
            get {
                return ResourceManager.GetString("ShortCutKeyCtrlAltN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ctrl+Alt+Up Arrow.
        /// </summary>
        public static string ShortCutKeyCtrlAltUp {
            get {
                return ResourceManager.GetString("ShortCutKeyCtrlAltUp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ctrl+C.
        /// </summary>
        public static string ShortCutKeyCtrlC {
            get {
                return ResourceManager.GetString("ShortCutKeyCtrlC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ctrl+E, Ctrl+W.
        /// </summary>
        public static string ShortCutKeyCtrlECtrlW {
            get {
                return ResourceManager.GetString("ShortCutKeyCtrlECtrlW", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ctrl+Enter.
        /// </summary>
        public static string ShortCutKeyCtrlEnter {
            get {
                return ResourceManager.GetString("ShortCutKeyCtrlEnter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ctrl+L.
        /// </summary>
        public static string ShortCutKeyCtrlL {
            get {
                return ResourceManager.GetString("ShortCutKeyCtrlL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ctrl+S.
        /// </summary>
        public static string ShortCutKeyCtrlS {
            get {
                return ResourceManager.GetString("ShortCutKeyCtrlS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ctrl+Shift+C.
        /// </summary>
        public static string ShortCutKeyCtrlShiftC {
            get {
                return ResourceManager.GetString("ShortCutKeyCtrlShiftC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ctrl+Shift+S.
        /// </summary>
        public static string ShortCutKeyCtrlShiftS {
            get {
                return ResourceManager.GetString("ShortCutKeyCtrlShiftS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ctrl+V.
        /// </summary>
        public static string ShortCutKeyCtrlV {
            get {
                return ResourceManager.GetString("ShortCutKeyCtrlV", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ctrl+X.
        /// </summary>
        public static string ShortCutKeyCtrlX {
            get {
                return ResourceManager.GetString("ShortCutKeyCtrlX", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Enter.
        /// </summary>
        public static string ShortCutKeyEnter {
            get {
                return ResourceManager.GetString("ShortCutKeyEnter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Esc.
        /// </summary>
        public static string ShortCutKeyEscape {
            get {
                return ResourceManager.GetString("ShortCutKeyEscape", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Shift+Enter.
        /// </summary>
        public static string ShortCutKeyShiftEnter {
            get {
                return ResourceManager.GetString("ShortCutKeyShiftEnter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Show Line Numbers.
        /// </summary>
        public static string ShowLineNumbersCommand {
            get {
                return ResourceManager.GetString("ShowLineNumbersCommand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Text Files.
        /// </summary>
        public static string TextFiles {
            get {
                return ResourceManager.GetString("TextFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Visual Basic Script Files.
        /// </summary>
        public static string VisualBasicScriptFiles {
            get {
                return ResourceManager.GetString("VisualBasicScriptFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a C# Interactive.
        /// </summary>
        public static string Window_CSharp {
            get {
                return ResourceManager.GetString("Window_CSharp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Visual Basic Interactive.
        /// </summary>
        public static string Window_VisualBasic {
            get {
                return ResourceManager.GetString("Window_VisualBasic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a _Word Wrap.
        /// </summary>
        public static string WordWrapHeader {
            get {
                return ResourceManager.GetString("WordWrapHeader", resourceCulture);
            }
        }
    }
}
